build: add experimental TSAN configuration (#3328)

diff --git a/.github/workflows/sanitizer.yml b/.github/workflows/sanitizer.yml
--- a/.github/workflows/sanitizer.yml
+++ b/.github/workflows/sanitizer.yml
@@ -3,7 +3,7 @@ name: Sanitizer checks
 on: [push, pull_request]
 
 jobs:
-  asan:
+  sanitizers:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -12,6 +12,12 @@ jobs:
           sudo apt-get install ninja-build
       - name: Envinfo
         run: npx envinfo
+      - name: TSAN
+        run: |
+          mkdir build-tsan
+          (cd build-tsan && cmake .. -G Ninja -DBUILD_TESTING=ON -DTSAN=ON -DCMAKE_BUILD_TYPE=Release)
+          cmake --build build-tsan
+          ./build-tsan/uv_run_tests_a || true # currently permit failures
       - name: ASAN
         run: |
           mkdir build-asan
